### PR TITLE
Adjust the layout of the credits page for smaller screen

### LINKED ISSUE #83: Fix the credits page layout for smaller screen size
**Describe the problem**
The back button on the credits page sits on the main content when the screen height is small.

### PR DESCRIPTION
**Pull request by mpark4656**
Fixed credits page layout on smaller screen

### CODE REVIEW

**Comment by cristianUrbina** [comment]
Sorry michael, I think you forget to pull dev changes and then rebase dev from your topic branch, there are a lot of changes that are actually merged into dev. Please pull dev changes then rebase from you topic branch and the open a pull request.

**Comment by cristianUrbina** [comment]
I see the problem, you are trying to merge into main and not into dev.

**Comment by mpark4656** [comment]
> I see the problem, you are trying to merge into main and not into dev.

Haha, ya, the fact that it keeps defaulting to main as the target branch gets me

**Comment by mpark4656** [comment]
Reopened and changed the target branch to dev

**Review by cristianUrbina — APPROVED** [review]
Looks great. Nice job 😄

**Pull request merged**
