### PR TITLE
Fix the issue with animation stopping

### LINKED ISSUE #13: Create Game page with falling words to be typed
As a player,
I want to see a functioning game screen
So that I can play the game

I want to see:

- [ ] ~~A prompt at the start to enter my name - The application will address me by the name I provide throughout the game (For example: "Hello, [NAME], the game will start soon!", "[Name], the game has ended, here is your game summary.").~~
- [x] A textbox to indicate player's WPM
- [ ] ~~A Start/Stop button~~
- [x] Random words falling from the top of the page to the bottom when the game starts
- [x] Hearts that represent the number of Lives that I have. A heart can represent one life. If I fail to type a word, I would see one of the hearts on the game screen disappear.
- [x] A running score while I play the game

### PR DESCRIPTION
**Pull request by mpark4656**
Fixed the issue with animation stopping when the stop function is invoked inside executeFrameActions.

we no longer need to maintain the frameIntervalId for the game frame with this new approach. The recursion will continue only when this.gameInProgress is true, so once that flag is set to false, the frame actions will stop.

### CODE REVIEW

**Comment by cristianUrbina** [comment]
I tested the code and works well, but I don't understand how was the bug produced since I did checkout the commit before the last one and works well too. Can you state steps to reproduce the bug please?

**Comment by cristianUrbina** [comment]
> I tested the code and works well, but I don't understand how was the bug produced since I did checkout the commit before the last one and works well too. Can you state steps to reproduce the bug please?

Forget about this, I already could reproduce the bug. I don't know what happened the first time I try.

**Review by cristianUrbina — COMMENTED** [review]
Code looks great but I think the commit message is kinda large to be a one line message. For messages with more than 50 characters, I would suggest to use a format similar to the example here https://udacity.github.io/git-styleguide/

**Comment by mpark4656** [comment]
> Code looks great but I think the commit message is kinda large to be a one line message. For messages with more than 50 characters, I would suggest to use a format similar to the example here https://udacity.github.io/git-styleguide/

I appreciate the tips! Since I am not using Git on a regular basis, I'd love to learn some guidelines and tips such as the ones you provide. Really appreciate it  :)

**Comment by mpark4656** [comment]
I fixed the commit message. Had to rebase in the process.

**Review by cristianUrbina — APPROVED** [review]
Looks a lot better now.

**Pull request merged**
