### PR TITLE
Fun Facts Page - Issue #20

### LINKED ISSUE #20: Create Fun facts Page
As a player
I want to see some interesting facts or trivia about typing and some famous typists around the world
So that I can gain more knowledge on the subject of typing

### PR DESCRIPTION
**Pull request by mpark4656**
Completed the basic fun facts page

### CODE REVIEW

**Review by cristianUrbina — COMMENTED** [review]
Tab chars look weird on GitHub and reviewing the code locally I notice you used 2-spaces tabs. Am I wrong :question: If not, you should change them for 4-spaces tabs I order to meet team's codings standards :smile: .

**Comment by cristianUrbina** [comment]
> Tab chars look weird on GitHub and reviewing the code locally I notice you used 2-spaces tabs. Am I wrong question If not, you should change them for 4-spaces tabs I order to meet team's codings standards smile .

It is worth to mention that this is only for the trivia.html file :smile: .

**Comment by mpark4656** [comment]
I think it's fixed now. It was originally set up 4-space width tab, but for some reason vscode's tab setting doesn't seem to translate well on Github. I changed vscode to use 4 spaces instead of a tab of 4 space width to fix it.

**Review by cristianUrbina — APPROVED** [review]
Awesome :smile:

**Pull request merged**
