### PR TITLE
Feature/game over screen 17

### LINKED ISSUE #17: Create Game over screen indicating score
As a player
I want to see a screen that tells me the Game is Over and displays my score details
So that I can see how I performed during the game

I want to see:

- [x] the game summary in a modal.
- [x] the total score and the time elapsed in the game summary
- [x] the total number of words that I have typed successfully. (Should Have)
- [ ] how many times I have entered misspelled words (Incorrectly typed any words and hit Enter/Space key). (Should Have)
- [ ] how many times I have pressed the Backspace button to make corrections while typing words. (Should Have)

### PR DESCRIPTION
**Pull request by mpark4656**
The player performance stats are now displayed.
Minor styling changes

### CODE REVIEW

**Review by cristianUrbina — CHANGES_REQUESTED** [review]
You are using a 8-spaces tabs on all the js files as well as in the html file. In order to meet team's coding standards you have to change them for 4-spaces tabs 😄

**Comment by mpark4656** [comment]
Hmm... you are right. It does show more spaces (8) on github. But my local IDE (vscode) is set to tab with 4 spaces. Let me look into this. I think this also created many more changes than I actually made...

**Comment by mpark4656** [comment]
Learned something new. I adjusted the tab width settings in vscode and it looks better now.

**Review by sorensoroush — APPROVED** [review]

**Review by cristianUrbina — APPROVED** [review]
Everything seems to work perfectly. Sorry for the lateness, I had a tough time reviewing this.

**Pull request merged**
